#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# has HAYSTACK NEEDLE — substring test that avoids pipes. This script runs with
# pipefail, and `grep -q` exits on first match, sending SIGPIPE upstream; the
# pipeline then reports failure even though the match succeeded.
has() { case "$1" in *"$2"*) return 0 ;; *) return 1 ;; esac; }

TEAM_ID="${TEAM_ID:-}"
NOTARY_PROFILE="MyQuickFinder"
SCHEME="MyQuickFinder"
APP_NAME="MyQuickFinder.app"

cd "$(git rev-parse --show-toplevel)"

BUILD_DIR="$(pwd)/.release-build"
ARTIFACT_DIR="$(pwd)/.release-artifacts"
VERSION=$(awk -F'"' '/MARKETING_VERSION:/ { print $2; exit }' project.yml)
TAG="v${VERSION}"
ZIP="${ARTIFACT_DIR}/MyQuickFinder-${VERSION}.zip"

banner "Release MyQuickFinder ${TAG}"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "A release must start from a clean main, or what you ship won't match the repo."

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ -n "$(git status --porcelain)" ]]; then
  warn "Uncommitted changes. Commit or stash them first."; exit 1
fi
note "branch: ${BRANCH}    version: ${VERSION}    tag: ${TAG}"
if [[ "$BRANCH" != "main" ]]; then
  confirm "Not on main. Continue anyway?" || exit 1
fi
if git rev-parse "$TAG" >/dev/null 2>&1; then
  warn "${TAG} already exists. Bump MARKETING_VERSION in project.yml first."; exit 1
fi

say "Running the three gates…"
swift test --package-path MyQuickFinderKit >/dev/null 2>&1 && printf '  %s✓%s tests pass\n' "$GREEN" "$RESET" || { warn "tests failed"; exit 1; }
./scripts/lint.sh >/dev/null 2>&1 && printf '  %s✓%s lint passes\n' "$GREEN" "$RESET" || { warn "lint failed"; exit 1; }
pause "Preflight is clean. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Developer ID Application certificate"
say "This is the identity that lets other people run the app. A development"
say "certificate won't do — Gatekeeper rejects it on any other Mac."
printf '\n'

IDENTITIES=$(security find-identity -v -p codesigning 2>/dev/null || true)
if has "$IDENTITIES" "Developer ID Application"; then
  printf '  %s✓%s already installed, skipping\n' "$GREEN" "$RESET"
else
  warn "Not on this machine yet."
  step "Open Xcode → Settings… (⌘,) → Accounts"
  step "Select your Apple ID → Manage Certificates… (bottom right)"
  step "Click + (bottom left) → Developer ID Application"
  note "The private key is generated here. If the certificate lives on another"
  note "machine, export a .p12 from there and double-click it instead."
  note "Creating one requires the Account Holder or Admin role."
  pause "Press Enter once it's installed and I'll verify"
  IDENTITIES=$(security find-identity -v -p codesigning 2>/dev/null || true)
  if ! has "$IDENTITIES" "Developer ID Application"; then
    warn "Still not found. Check you picked Developer ID Application, not Development."; exit 1
  fi
  printf '  %s✓%s found it\n' "$GREEN" "$RESET"
fi

SIGN_ID=$(printf '%s\n' "$IDENTITIES" | awk -F'"' '/Developer ID Application/ { print $2; exit }')
note "signing with: ${SIGN_ID}"
TEAM_ID="${TEAM_ID:-$(printf '%s' "$SIGN_ID" | sed -n 's/.*(\([A-Z0-9]*\))$/\1/p')}"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App-specific password"
say "Notarization authenticates to Apple with an app-specific password —"
say "not your Apple ID password."
printf '\n'

if xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
  printf '  %s✓%s notarization credentials already stored, skipping this and the next stage\n' "$GREEN" "$RESET"
  SKIP_CREDENTIALS=yes
else
  SKIP_CREDENTIALS=no
  open_url "https://appleid.apple.com/account/manage"
  step "Sign in, then find Sign-In and Security → App-Specific Passwords"
  step "Generate one — name it anything, e.g. MyQuickFinder notarization"
  step "Copy it. It is shown exactly once."
  warn "Don't paste it into a chat window or a file. Apple's own tool takes it next."
  pause "Press Enter once you've copied it"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Store it in the keychain"
if [[ "$SKIP_CREDENTIALS" == "yes" ]]; then
  printf '  %s✓%s already stored, skipping\n' "$GREEN" "$RESET"
else
  say "notarytool will prompt for your Apple ID and that password, then keep them"
  say "in the keychain. After this, releases reference it by profile name only."
  printf '\n'
  ask APPLE_ID "Your Apple ID (email):"
  printf '\n'
  note "notarytool will now ask for the app-specific password — paste it:"
  printf '\n'
  xcrun notarytool store-credentials "$NOTARY_PROFILE" \
    --apple-id "$APPLE_ID" --team-id "$TEAM_ID"
  printf '\n'
  if ! xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
    warn "Stored, but unusable. Usually a mistyped password — rerun this stage."; exit 1
  fi
  printf '  %s✓%s credentials work\n' "$GREEN" "$RESET"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Build with Developer ID"
warn "Changing signing identity means a different program as far as macOS is concerned."
note "Granted folder permissions and the registered login item reset once."
note "One-time; it's stable afterwards."
printf '\n'
confirm "Understood — start the build?" || exit 1

rm -rf "$BUILD_DIR" "$ARTIFACT_DIR"
mkdir -p "$ARTIFACT_DIR"
BUILD_NUMBER=$(git rev-list --count HEAD)
note "build number: ${BUILD_NUMBER} (commit count — monotonic, no hand-editing)"
say "Building (about a minute)…"
xcodebuild -project MyQuickFinder.xcodeproj -scheme "$SCHEME" \
  -configuration Release -destination 'platform=macOS' \
  -derivedDataPath "$BUILD_DIR" \
  CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
  CODE_SIGN_IDENTITY="$SIGN_ID" \
  CODE_SIGN_STYLE=Manual \
  DEVELOPMENT_TEAM="$TEAM_ID" \
  CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO \
  OTHER_CODE_SIGN_FLAGS="--timestamp --options runtime" \
  build >/dev/null 2>&1 || { warn "Build failed. Rerun without >/dev/null to see why."; exit 1; }

APP="${BUILD_DIR}/Build/Products/Release/${APP_NAME}"
[[ -d "$APP" ]] || { warn "No build product at $APP"; exit 1; }
SIGN_INFO=$(codesign -dvv "$APP" 2>&1 || true)
has "$SIGN_INFO" "Developer ID Application" \
  || { warn "The product is not Developer ID signed"; printf '%s\n' "$SIGN_INFO" | sed 's/^/    /'; exit 1; }
ENTITLEMENTS=$(codesign -d --entitlements - --xml "$APP" 2>/dev/null || true)
if has "$ENTITLEMENTS" "get-task-allow"; then
  warn "The product carries get-task-allow, the debug entitlement. Apple will reject it."
  note "The build is missing CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO"
  exit 1
fi
printf '  %s✓%s built and signed with Developer ID\n' "$GREEN" "$RESET"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Notarize"
say "Hand the app to Apple to scan. Usually a minute or two, sometimes fifteen."
printf '\n'
ditto -c -k --keepParent "$APP" "$ZIP"
say "Uploaded. Waiting on Apple…"
NOTARY_OUT=$(xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait 2>&1 || true)
printf '%s\n' "$NOTARY_OUT" | sed 's/^/    /'
SUBMISSION_ID=$(printf '%s\n' "$NOTARY_OUT" | awk '/^ *id:/ { print $2; exit }')
if has "$NOTARY_OUT" "status: Accepted"; then
  printf '  %s✓%s notarized\n' "$GREEN" "$RESET"
else
  warn "Notarization did not pass. Apple's reason:"
  if [[ -n "$SUBMISSION_ID" ]]; then
    xcrun notarytool log "$SUBMISSION_ID" --keychain-profile "$NOTARY_PROFILE" 2>&1 | sed 's/^/    /'
  fi
  exit 1
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Staple and verify"
say "Staple the ticket into the app so it validates offline too."
printf '\n'
xcrun stapler staple "$APP" || { warn "Stapling failed"; exit 1; }

say "Verify — this is the evidence that other people can actually open it:"
xcrun stapler validate "$APP" >/dev/null 2>&1 \
  && printf '  %s✓%s ticket stapled\n' "$GREEN" "$RESET" \
  || { warn "Ticket is not stapled"; exit 1; }

GATEKEEPER=$(spctl -a -vvv -t install "$APP" 2>&1 || true)
if has "$GATEKEEPER" "accepted"; then
  printf '  %s✓%s Gatekeeper accepts it\n' "$GREEN" "$RESET"
else
  warn "Gatekeeper rejects it — do not ship"
  printf '%s\n' "$GATEKEEPER" | sed 's/^/    /'
  exit 1
fi

rm -f "$ZIP"
ditto -c -k --keepParent "$APP" "$ZIP"
note "repackaged with the ticket: $(basename "$ZIP")"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Tag and publish"
say "This pushes the tag and creates the GitHub release."
note "The repo is private, so the release is visible only to people with access."
printf '\n'
printf '%s\n' "$(gh auth status 2>&1 || true)" | awk '/Logged in/ { print "  " $0 }'
printf '\n'
confirm "Publish ${TAG}?" || { note "Not published. The artifact is at ${ZIP}"; exit 0; }

git tag -a "$TAG" -m "MyQuickFinder ${VERSION}"
git push origin "$TAG"
gh release create "$TAG" "$ZIP" \
  --title "MyQuickFinder ${VERSION}" \
  --notes "Signed with Developer ID, notarized by Apple, ticket stapled. Unzip and drag into Applications."

printf '  %s✓%s published\n' "$GREEN" "$RESET"
finish
note "artifact: ${ZIP}"
note "Next release: bump MARKETING_VERSION in project.yml and rerun this script."
note "Certificate and credentials are stored — stages 2–4 will skip themselves."
