#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# has HAYSTACK NEEDLE — 子串判定。不走管道：本脚本开了 pipefail，而 grep -q
# 匹配后立刻退出会让上游收到 SIGPIPE，整条管道被判失败，匹配成功反被当成失败。
has() { case "$1" in *"$2"*) return 0 ;; *) return 1 ;; esac; }

# first_match PATTERN FILE — 第一条匹配行，用 awk 一次读完，不用 head 截断管道。
first_match() { awk "/$1/ { print; exit }" "$2"; }

TEAM_ID="${TEAM_ID:-}"
NOTARY_PROFILE="MyQuickFinder"
SCHEME="MyQuickFinder"
APP_NAME="MyQuickFinder.app"
cd "$(git rev-parse --show-toplevel)"

BUILD_DIR="$(pwd)/.release-build"
ARTIFACT_DIR="$(pwd)/.release-artifacts"
VERSION=$(awk -F'"' '/MARKETING_VERSION:/ { print $2; exit }' project.yml)
TAG="v${VERSION}"
ZIP="${ARTIFACT_DIR}/MyQuickFinder-${VERSION}.zip"

banner "MyQuickFinder ${TAG} 发布"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "前置检查"
say "发布必须从干净的 main 出发，否则你发出去的和仓库里的对不上。"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ -n "$(git status --porcelain)" ]]; then
  warn "工作区有未提交的改动，先提交或 stash。"; exit 1
fi
note "分支：${BRANCH}    版本：${VERSION}    tag：${TAG}"
if [[ "$BRANCH" != "main" ]]; then
  confirm "当前不在 main 上，仍要继续？" || exit 1
fi
if git rev-parse "$TAG" >/dev/null 2>&1; then
  warn "${TAG} 已经存在。要发新版本，先在 project.yml 里改 MARKETING_VERSION。"; exit 1
fi

say "跑三个闸……"
swift test --package-path MyQuickFinderKit >/dev/null 2>&1 && printf '  %s✓%s 测试通过\n' "$GREEN" "$RESET" || { warn "测试没过"; exit 1; }
./scripts/lint.sh >/dev/null 2>&1 && printf '  %s✓%s lint 通过\n' "$GREEN" "$RESET" || { warn "lint 没过"; exit 1; }
pause "前置都干净，继续？"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Developer ID Application 证书"
say "这是能给别人用的签名身份。开发用的 Apple Development 证书不行——"
say "装到别人机器上会被 Gatekeeper 直接拒绝。"
printf '\n'

IDENTITIES=$(security find-identity -v -p codesigning 2>/dev/null || true)
if has "$IDENTITIES" "Developer ID Application"; then
  printf '  %s✓%s 已经装好了，跳过\n' "$GREEN" "$RESET"
else
  warn "这台机器上还没有。"
  step "打开 Xcode → Settings…（⌘,）→ Accounts"
  step "选中你的 Apple ID → 右下角 Manage Certificates…"
  step "左下角 + → 选 Developer ID Application"
  note "私钥会在这台机器上生成。如果证书在另一台机器上，改从那边导出 .p12 再双击导入。"
  note "创建 Developer ID 证书需要 Account Holder 或 Admin 角色。"
  pause "装好之后按 Enter，我来验证"
  IDENTITIES=$(security find-identity -v -p codesigning 2>/dev/null || true)
  if ! has "$IDENTITIES" "Developer ID Application"; then
    warn "还是没找到。确认证书类型选的是 Developer ID Application，不是 Development。"; exit 1
  fi
  printf '  %s✓%s 找到了\n' "$GREEN" "$RESET"
fi

SIGN_ID=$(printf '%s\n' "$IDENTITIES" | awk -F'"' '/Developer ID Application/ { print $2; exit }')
note "将用于签名：${SIGN_ID}"
TEAM_ID="${TEAM_ID:-$(printf '%s' "$SIGN_ID" | sed -n 's/.*(\([A-Z0-9]*\))$/\1/p')}"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App 专用密码"
say "公证要向 Apple 认证。用 App 专用密码，不是你的 Apple ID 密码。"
printf '\n'

if xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
  printf '  %s✓%s 公证凭据已经配好了，跳过这步和下一步\n' "$GREEN" "$RESET"
  SKIP_CREDENTIALS=yes
else
  SKIP_CREDENTIALS=no
  open_url "https://appleid.apple.com/account/manage"
  step "登录后找「登录与安全」→「App 专用密码」"
  step "点「生成密码…」，名字随便写，比如 MyQuickFinder 公证"
  step "复制它——密码只显示这一次"
  warn "别把它贴进聊天窗口或任何文件；下一步由 Apple 的工具直接收走。"
  pause "复制好了按 Enter"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "存进钥匙串"
if [[ "$SKIP_CREDENTIALS" == "yes" ]]; then
  printf '  %s✓%s 已配好，跳过\n' "$GREEN" "$RESET"
else
  say "notarytool 会自己问你要 Apple ID 与刚才那个密码，然后存进钥匙串。"
  say "之后每次发布只用 profile 名字调它，密码不再出现。"
  printf '\n'
  ask APPLE_ID "你的 Apple ID（邮箱）："
  printf '\n'
  note "接下来 notarytool 会提示 App-specific password，粘贴刚复制的那串："
  printf '\n'
  xcrun notarytool store-credentials "$NOTARY_PROFILE" \
    --apple-id "$APPLE_ID" --team-id "$TEAM_ID"
  printf '\n'
  if ! xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
    warn "凭据存了但用不了。多半是密码贴错，重跑这一步。"; exit 1
  fi
  printf '  %s✓%s 凭据可用\n' "$GREEN" "$RESET"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "用 Developer ID 构建"
warn "换签名身份 = 系统眼里换了一个程序。"
note "已授予的文件访问权限和已注册的登录项会重置一次，需要重新授权。"
note "这是一次性的，之后就稳定了。"
printf '\n'
confirm "知道了，开始构建？" || exit 1

rm -rf "$BUILD_DIR" "$ARTIFACT_DIR"
mkdir -p "$ARTIFACT_DIR"
BUILD_NUMBER=$(git rev-list --count HEAD)
note "build number：${BUILD_NUMBER}（提交数，单调递增，不用手改）"
say "构建中（几十秒）……"
xcodebuild -project MyQuickFinder.xcodeproj -scheme "$SCHEME" \
  -configuration Release -destination 'platform=macOS' \
  -derivedDataPath "$BUILD_DIR" \
  CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
  CODE_SIGN_IDENTITY="$SIGN_ID" \
  CODE_SIGN_STYLE=Manual \
  DEVELOPMENT_TEAM="$TEAM_ID" \
  CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO \
  OTHER_CODE_SIGN_FLAGS="--timestamp --options runtime" \
  build >/dev/null 2>&1 || { warn "构建失败，去掉 >/dev/null 重跑看报错"; exit 1; }

APP="${BUILD_DIR}/Build/Products/Release/${APP_NAME}"
[[ -d "$APP" ]] || { warn "没找到构建产物：$APP"; exit 1; }
SIGN_INFO=$(codesign -dvv "$APP" 2>&1 || true)
has "$SIGN_INFO" "Developer ID Application" \
  || { warn "产物不是用 Developer ID 签的"; printf '%s\n' "$SIGN_INFO" | sed 's/^/    /'; exit 1; }
ENTITLEMENTS=$(codesign -d --entitlements - --xml "$APP" 2>/dev/null || true)
if has "$ENTITLEMENTS" "get-task-allow"; then
  warn "产物带着 get-task-allow（调试用的授权），Apple 一定会拒"
  note "构建时漏了 CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO"
  exit 1
fi
printf '  %s✓%s 构建完成并已用 Developer ID 签名，无调试授权\n' "$GREEN" "$RESET"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "公证"
say "把 app 交给 Apple 扫一遍。通常一两分钟，慢的时候十几分钟。"
printf '\n'
ditto -c -k --keepParent "$APP" "$ZIP"
say "已上传，等 Apple 回话……"
NOTARY_OUT=$(xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait 2>&1 || true)
printf '%s\n' "$NOTARY_OUT" | sed 's/^/    /'
SUBMISSION_ID=$(printf '%s\n' "$NOTARY_OUT" | awk '/^ *id:/ { print $2; exit }')
if has "$NOTARY_OUT" "status: Accepted"; then
  printf '  %s✓%s 公证通过\n' "$GREEN" "$RESET"
else
  warn "公证没通过，Apple 给的原因："
  if [[ -n "$SUBMISSION_ID" ]]; then
    xcrun notarytool log "$SUBMISSION_ID" --keychain-profile "$NOTARY_PROFILE" 2>&1 | sed 's/^/    /'
  fi
  exit 1
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "钉票据并验证"
say "把公证票据钉进 app，这样断网也能通过校验。"
printf '\n'
xcrun stapler staple "$APP" || { warn "钉票据失败"; exit 1; }

say "验证——这一步才是「真的能给别人用」的证据："
xcrun stapler validate "$APP" >/dev/null 2>&1 \
  && printf '  %s✓%s 票据已钉上\n' "$GREEN" "$RESET" \
  || { warn "票据没钉上"; exit 1; }
GATEKEEPER=$(spctl -a -vvv -t install "$APP" 2>&1 || true)
if has "$GATEKEEPER" "accepted"; then
  printf '  %s✓%s Gatekeeper 接受\n' "$GREEN" "$RESET"
else
  warn "Gatekeeper 不接受，别发"
  printf '%s\n' "$GATEKEEPER" | sed 's/^/    /'
  exit 1
fi

rm -f "$ZIP"
ditto -c -k --keepParent "$APP" "$ZIP"
note "已重新打包（这次带票据）：$(basename "$ZIP")"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "打 tag，建 release"
say "最后一步会推 tag 并在 GitHub 上建 release。"
note "仓库是 private，release 只有有权限的人看得到。"
printf '\n'
printf '%s\n' "$(gh auth status 2>&1 || true)" | awk '/Logged in/ { print "  " $0 }'
printf '\n'
confirm "确认发布 ${TAG}？" || { note "没发。产物在 ${ZIP}"; exit 0; }

git tag -a "$TAG" -m "MyQuickFinder ${VERSION}"
git push origin "$TAG"
gh release create "$TAG" "$ZIP" \
  --title "MyQuickFinder ${VERSION}" \
  --notes "已用 Developer ID 签名并经 Apple 公证，票据已钉入 app。下载解压即可拖进「应用程序」。"

printf '  %s✓%s 已发布\n' "$GREEN" "$RESET"
finish
note "产物：${ZIP}"
note "下次发布：改 project.yml 里的 MARKETING_VERSION，再跑一次这个脚本。"
note "证书与公证凭据已经存好，第 2–4 步会自动跳过。"
